---

- name: Ensure ceph directory exists
  file:
    path: /etc/ceph
    state: directory
    mode: 0700

- block:
  - name: Create secret file for CephFS user directory
    copy:
      content: "{{ item['key'] }}"
      dest: "/etc/ceph/cephfs_{{ item['id'] }}_secret"
      force: no
    loop: "{{ cephfs_client_mapping }}"

  - name: CephFS directory mappings
    mount:
      path: "{{ item['dst'] }}"
      src: "{{ ceph_monitor | join(',') }}:6789:{{ item['src'] }}"
      fstype: ceph
      opts: "name={{ item['id'] }},secretfile=/etc/ceph/cephfs_{{ item['id'] }}_secret,_netdev"
      state: mounted
    loop: "{{ cephfs_client_mapping }}"
