---

# Variable configuration.
- name: Include OS-specific variables for Ubuntu based machines.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version}}.yml"

# Freeipa variables.
- name: Include CephFS mount variables.
  include_vars: "cephfs_mounts.yml"